#include "stdafx.h"
#include <iostream>
using namespace std;
//■問題1
// try catch で、チェックしたい対象の範囲を囲えばよい
void f(){
	for (int i = 0; i < 10; i++) {
		for (int j = 0; j < 10; j++) {
			cout << "i:" << i << " j:" << j << endl;
			// i==5かつj==5のときに runtime_error の例外処理
			// を発生させて、i,jのループを中断してください。
			if (i == 5 && j == 5) throw runtime_error("runtime_error");
		}
	}
}

int _tmain(int argc, _TCHAR* argv[]){

	try {
		f(); // f()の中でcatchする方法と、その外でcatch する方法がある
	}
	catch (exception& e)
	{
		cerr << "main:" << e.what() << endl;
	}

	return 0;
}

